# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aa4aa4f084a87180705053ed4fb3ae56"
application_url = "https://45ee-2401-4900-889a-a608-687e-c683-c985-8a77.ngrok-free.app"
embedded = true
name = "test-new"
handle = "test-new-52"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://45ee-2401-4900-889a-a608-687e-c683-c985-8a77.ngrok-free.app/auth/callback",
  "https://45ee-2401-4900-889a-a608-687e-c683-c985-8a77.ngrok-free.app/auth/shopify/callback",
  "https://45ee-2401-4900-889a-a608-687e-c683-c985-8a77.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
